### ISSUE TITLE
Can I use Energenie MIHO002 with this plugin?

### ISSUE THREAD

**Issue by Ricardo1980** [suda/homebridge-platform-energenie#1]
Can I use Energenie-MIHO002 with this plugin?
Thanks

https://www.amazon.co.uk/Energenie-MIHO002-Adapters-Pack-3/dp/B00V52HTJC/ref=pd_vtph_60_tr_t_2?ie=UTF8&refRID=R1VC06NTFKZR34H5EDCY

**Comment by suda** [comment]
If you have https://www.amazon.co.uk/gp/aw/d/B00P3JIUQO/ref=mp_s_a_1_9?qid=1464598014&sr=8-9&pi=AC_SX236_SY340_QL65&keywords=Energenie plugged into your Rasperry Pi then yes, it should :)

**Comment by Ricardo1980** [comment]
Thanks!

**Comment by The-Benjamin-Leo** [comment]
Do you have to have the PI mote in order for this plugin to work?
